Update readme.md
IntroToCode/Spring21_Recipes_Codemates15 pull request #4
Opened 2021-03-30 03:27 UTC by ccastilloux

## 🎯 Objective

_Note why you're making this change and any relevant issues_

## 🛠️ Changes made

_Note what you actual changes you're proposing_ 

## 👥 Who needs to review this Pull Request? 

_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

2021-03-30 03:33 UTC, Justinli90 commented
@ccastilloux can we consider thick cut bacon instead of regular bacon? 😋😋

2021-03-30 03:33 UTC, lancebarnardberkeley commented
should we do scrambled or poached??

2021-03-30 03:42 UTC, ccastilloux commented
@Justinli90 No problem 👍🏽
@lancebarnardberkeley Good call, made it so eggs can be made to the cook's preference!

2021-03-30 03:47 UTC, Justinli90 commented
In my experience it takes closer to 20 minutes to cook a recipe like this. Changing to 20 minutes! Feel free to change back if you disagree 😁

Looks delicious guys!

@ccastilloux @lancebarnardberkeley

2021-04-02 22:07 UTC, Aleixsc commented
This looks delicious, but also a bit unhealthy. 
Could we add the option to use egg whites instead of whole eggs?

2021-04-02 22:08 UTC, Aleixsc commented
Changing the title to "Eggs and Crispy Bacon"

2021-04-02 23:26 UTC, Aleixsc requested changes

2021-04-02 23:26 UTC, Aleixsc commented on breakfast/readme.md
> +1. Crack all 8 eggs into a mixing bowl
Or crack 2 full eggs into a bowl, then separate white from yolks in another bowl, and add the whites to the 2 eggs.

2021-04-03 01:06 UTC, Justinli90 commented
> This looks delicious, but also a bit unhealthy.
> Could we add the option to use egg whites instead of whole eggs?
> 
> @ccastilloux @lancebarnardberkeley @Justinli90

@Aleixsc great call. Less cholesterol. Thanks for making these changes!

2021-04-03 01:09 UTC, Justinli90 commented
@lancebarnardberkeley @ccastilloux @Aleixsc If changes look good to you all, I will merge the PR. Thanks! 👊💪

2021-04-03 17:28 UTC, ccastilloux commented
@lancebarnardberkeley @Justinli90 @Aleixsc Looks good to me as well 👍

2021-04-03 21:07 UTC, Justinli90 commented
Approved from my side as well. Merging, thanks!  👍 😄

2021-04-03 21:07 UTC, merged